[build]
  command = "npm run build"
  publish = "build"
  # This line can stay or be removed
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"   # ðŸ‘ˆ THIS IS THE MISSING PIECE
  included_files = ["netlify/email_templates/*"]

[[scheduled]]
  name = "nightly-reminders"
  cron = "50 1 * * *"
  function = "nightlyReminders"
